export const COLORS = {
  primary: "#00490e",
  primaryContainer: "#0d631b",
  onPrimary: "#ffffff",
  secondary: "#8f4e00",
  secondaryContainer: "#ff8f04",
  onSecondary: "#ffffff",
  background: "#f7fbf1",
  surface: "#f7fbf1",
  surfaceContainer: "#ebefe5",
  surfaceContainerLow: "#f1f5eb",
  surfaceContainerHigh: "#e5eae0",
  surfaceContainerHighest: "#e0e4da",
  surfaceContainerLowest: "#ffffff",
  onSurface: "#181d17",
  onSurfaceVariant: "#40493d",
  outlineVariant: "#bfcaba",
  outline: "#707a6c",
  error: "#ba1a1a",
  onError: "#ffffff",
  success: "#2e7d32",
  onSuccess: "#ffffff",
  warning: "#ff8f04",
  onWarning: "#ffffff",
};